[options]
admin_passwd = CHANGE_ME
db_host = localhost
db_port = 5432
db_user = odoo
db_password = CHANGE_ME
db_name = odoo
addons_path = /opt/odoo/odoo-server/addons,/opt/odoo/custom-addons
logfile = /var/log/odoo/odoo-server.log
log_level = info
xmlrpc_port = 8069
gevent_port = 8072
proxy_mode = True
workers = 3
max_cron_threads = 1
limit_memory_hard = 1677721600
limit_memory_soft = 629145600
limit_time_cpu = 600
limit_time_real = 1200
list_db = False
dbfilter = ^odoo$
